### ISSUE TITLE
[scaffodling-chef-infra] Unable to retrieve dependent cookbooks with Git credentials from private git repositories

### ISSUE THREAD

**Issue by msgarbossa** [chef/effortless#177]
There isn't a way to pass in Git credentials to `hab pkg build`.  Specifically, I'm trying to use SSH key authentication to Git for local builds and non-interactive builds in a pipeline job.  The SSH private key cannot be committed to Git, but it is needed in the clean room to retrieve dependent cookbooks from Git when `chef install` runs.

The policyfile tries to retrieve multiple dependent cookbooks from Git.

```ruby
cookbook 'os_hardening', git: 'git@github.com:myuser/os_hardening.git'
```
Error from `hab pkg build`:

```bash
Expanded run list: recipe[os_hardening::default]
Caching Cookbooks...
Installing os_hardening         >= 0.0.0 from git
Error: Failed to generate Policyfile.lock
Reason: (CookbookOmnifetch::GitCommandError) Git error: command `git clone git@github.com:myuser/os_hardening.git "/root/.chefdk/cache/.cache/git/f25db8fc19abdecb773c80f7d2cfde54a9d9bf90" --bare --no-hardlinks` failed. If this error persists, try removing the cache directory at '/root/.chefdk/cache/.cache/git/f25db8fc19abdecb773c80f7d2cfde54a9d9bf90'.Output from the command:
```

**Comment by msgarbossa** [comment]
I have a workaround using a wrapper script to build the Habitat package, but it shouldn't be this much work.  The basic premise is to have 2 policyfiles.  The first policyfile contains the cookbook/git statements and is run outside of Habitat to build a clean cookbook cache.  The second policyfile is used by `hab pkg build` and contains `default_source :chef_repo, "../"` so the cookbooks can be found locally.  Below is the workaround I tested with a little more detail.

1. Set home directory to the package workspace, ensure ~/.hab files exist.
2. export any build related variables (HAB_BLDR_URL, HAB_ORIGIN, HAB_AUTH_TOKEN, HAB_LICENSE, CHEF_LICENSE)
3. chef install <policyfile w/ git SSH links>.  The cookbooks will be cached in ~/.chefdk/cache/cookbooks.
4. mv ~/.chefdk/cache/cookbooks to the workspace root
5. hab pkg build .
6. . ./results/last_build.env
7. hab pkg upload ./results/${pkg_artifact}
8. cleanup

**Comment by TheLunaticScripter** [comment]
@msgarbossa thank you for opening this we will take a look.

**Comment by robertjskelton** [comment]
Hi, we are experiencing this same problem.

**Comment by TheLunaticScripter** [comment]
https://github.com/chef/effortless/issues/187

**Comment by TheLunaticScripter** [comment]
I did some research and opened an issue for this against [habitat](https://github.com/habitat-sh/habitat/issues/7568) and here are the results of what needs to be done to make this work. 

First, you need to be using the Habitat Docker Studio to do the builds. The reason for this  is so that you can mount your `.ssh` folder into the studio. Before launching the studio or running `hab pkg build` you need to set the `HAB_DOCKER_OPTS` environment variable. Here is an example of how to do this on Windows and Linux
windows:
```
$env:HAB_DOCKER_OPTS = 'c:/users/<your_username>/.ssh:<full path studio user>/.ssh'
```
Linux:
```
export HAB_DOCKER_OPTS='/home/<your_username>/.ssh:<full path studio user>/.ssh'
```
The user for a Linux studio is `root` and the user for a Windows studio is `ContainerAdministrator`.

If you are doing this on windows the file permissions for the ssh key won't work when building a Linux habitat package. To fix this, you will need to mount the `.ssh` directory to `/tmp` instead of directly to the `/root` location and then copy the directory to `/root/.ssh`. Once that is done you will then need to change the permissions on the `id_rsa` key as well as the `id_ras.pub` key so that chef can use it here is a little script to do that
```
cp -R /tmp/.ssh /root/.ssh
chmod 0700 /root/.ssh
chmod 0644 /root/.ssh/id_rsa.pub
chmod 0600 /root/.ssh/id_rsa
```

This should be all the steps needed to get you working with using git in your policyfiles.
